name: habits
description: Parallax scroll app based on Stian's UI.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0

  cupertino_icons: ^1.0.3
  rxdart: ^0.26.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  quiver: ^3.0.1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0
  smooth_page_indicator: ^0.2.3
  cached_network_image: 3.0.0
  flutter_swiper: ^1.1.6
  story_view: ^0.13.1
  provider: ^5.0.0
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  workmanager: ^0.2.3
  settings_ui: ^1.0.0
  timeline_tile: 0.1.2
  path_provider: ^2.0.1
  charts_flutter: ^0.10.0
  flutter_slidable: ^0.6.0
  heatmap_calendar: ^1.2.8
  sk_onboarding_screen: 1.0.1
  font_awesome_flutter: ^9.0.0
  flutter_calendar_carousel: ^2.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_local_notifications: ^6.0.0
  shared_preferences: ^2.0.5
  table_calendar: ^3.0.0
  lottie: 1.0.1
  flutter_web_browser: "^0.14.0"
  persistent_bottom_nav_bar: ^4.0.2
  simple_animations: ^1.3.3
  flutter_staggered_grid_view: 0.4.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
 
flutter:
  uses-material-design: true


  assets:
    - assets/svg/
    - assets/
    - assets/raw/
    - assets/fonts/
    - assets/images/
    - assets/topics/light/


fonts:
    
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf    
    - family: Nunito
      fonts:
        - asset: fonts/nunito.ttf